#!/bin/sh
# chkconfig: 235 99 10
# description: web-based account administration interface for Unix systems
#
### BEGIN INIT INFO
# Provides:          usermin
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: web-based account administration interface for Unix systems
# Description:       Usermin is a web-based interface for reading email, changing
#                    your password, setting up mail filters and more.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="web-based account administration interface for Unix systems"
NAME=Usermin
PIDFILE=/var/usermin/miniserv.pid
SCRIPTNAME=/etc/init.d/$NAME
START=/etc/usermin/start
STOP=/etc/usermin/stop
RELOAD=/etc/usermin/reload
LOCKFILE=/var/lock/subsys/usermin
CONFFILE=/etc/usermin/miniserv.conf

case "$1" in
start)
	$START >/dev/null 2>&1 </dev/null
	RETVAL=$?
	if [ "$RETVAL" = "0" ]; then
		touch $LOCKFILE >/dev/null 2>&1
	fi
	;;
stop)
	$STOP
	RETVAL=$?
	if [ "$RETVAL" = "0" ]; then
		rm -f $LOCKFILE
	fi
	pidfile=`grep "^pidfile=" $CONFFILE | sed -e 's/pidfile=//g'`
	if [ "$pidfile" = "" ]; then
		pidfile=$PIDFILE
	fi
	rm -f $pidfile
	;;
status)
	pidfile=`grep "^pidfile=" $CONFFILE | sed -e 's/pidfile=//g'`
	if [ "$pidfile" = "" ]; then
		pidfile=$PIDFILE
	fi
	if [ -s $pidfile ]; then
		pid=`cat $pidfile`
		kill -0 $pid >/dev/null 2>&1
		if [ "$?" = "0" ]; then
			echo "$NAME (pid $pid) is running"
			RETVAL=0
		else
			echo "$NAME is stopped"
			RETVAL=1
		fi
	else
		echo "$NAME is stopped"
		RETVAL=1
	fi
	;;
restart)
	$STOP ; $START
	RETVAL=$?
	;;
reload|force-reload)
	$RELOAD
	RETVAL=$?
	;;
*)
	echo "Usage: $0 {start|stop|restart|reload|force-reload|status}" >&2
	RETVAL=1
	;;
esac
exit $RETVAL

